// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXvpKlBtSxCrQBd--2HMuHIlOTvi3NE4s',
    appId: '1:113628914665:web:1315fe699f1fb3f3b2a178',
    messagingSenderId: '113628914665',
    projectId: 'bdd-llankay',
    authDomain: 'bdd-llankay.firebaseapp.com',
    storageBucket: 'bdd-llankay.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuvJzhDHI5JN2K3dNB2NhpF-rzJ07L5TU',
    appId: '1:113628914665:android:48c030c9f0c5cd94b2a178',
    messagingSenderId: '113628914665',
    projectId: 'bdd-llankay',
    storageBucket: 'bdd-llankay.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBXawPGN8kuL7AUGeZQ4a-OASAZ_jnEcE',
    appId: '1:113628914665:ios:692122b41b3d69b1b2a178',
    messagingSenderId: '113628914665',
    projectId: 'bdd-llankay',
    storageBucket: 'bdd-llankay.appspot.com',
    androidClientId: '113628914665-c72pnaqv7mhromc8omalr3gn7jn8bol1.apps.googleusercontent.com',
    iosClientId: '113628914665-i3cpfv23ckksupqvfk9kaa0ri4eeop7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.appLlankay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBXawPGN8kuL7AUGeZQ4a-OASAZ_jnEcE',
    appId: '1:113628914665:ios:139f7ee9505876b8b2a178',
    messagingSenderId: '113628914665',
    projectId: 'bdd-llankay',
    storageBucket: 'bdd-llankay.appspot.com',
    androidClientId: '113628914665-c72pnaqv7mhromc8omalr3gn7jn8bol1.apps.googleusercontent.com',
    iosClientId: '113628914665-d5nvaqntfs4gbiatjesh7aha5b05kl1s.apps.googleusercontent.com',
    iosBundleId: 'com.example.appLlankay.RunnerTests',
  );
}
